version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ledger_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/ledger_db
      - PYTHONPATH=/app
    command: bash -c "pip install -e /app/core && cd apps/app1 && alembic upgrade head && cd src && uvicorn main:app --host 0.0.0.0 --reload"

volumes:
  postgres_data: 